// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.25.1
// source: chough.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusMessage) Reset() {
	*x = StatusMessage{}
	mi := &file_chough_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusMessage) ProtoMessage() {}

func (x *StatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chough_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusMessage.ProtoReflect.Descriptor instead.
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return file_chough_proto_rawDescGZIP(), []int{0}
}

func (x *StatusMessage) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StatusMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReturnMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnMessage) Reset() {
	*x = ReturnMessage{}
	mi := &file_chough_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnMessage) ProtoMessage() {}

func (x *ReturnMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chough_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnMessage.ProtoReflect.Descriptor instead.
func (*ReturnMessage) Descriptor() ([]byte, []int) {
	return file_chough_proto_rawDescGZIP(), []int{1}
}

func (x *ReturnMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReturnMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type House struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *House) Reset() {
	*x = House{}
	mi := &file_chough_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *House) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*House) ProtoMessage() {}

func (x *House) ProtoReflect() protoreflect.Message {
	mi := &file_chough_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use House.ProtoReflect.Descriptor instead.
func (*House) Descriptor() ([]byte, []int) {
	return file_chough_proto_rawDescGZIP(), []int{2}
}

func (x *House) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Door struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Door) Reset() {
	*x = Door{}
	mi := &file_chough_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Door) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Door) ProtoMessage() {}

func (x *Door) ProtoReflect() protoreflect.Message {
	mi := &file_chough_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Door.ProtoReflect.Descriptor instead.
func (*Door) Descriptor() ([]byte, []int) {
	return file_chough_proto_rawDescGZIP(), []int{3}
}

func (x *Door) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DoorState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          bool                   `protobuf:"varint,1,opt,name=open,proto3" json:"open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoorState) Reset() {
	*x = DoorState{}
	mi := &file_chough_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoorState) ProtoMessage() {}

func (x *DoorState) ProtoReflect() protoreflect.Message {
	mi := &file_chough_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoorState.ProtoReflect.Descriptor instead.
func (*DoorState) Descriptor() ([]byte, []int) {
	return file_chough_proto_rawDescGZIP(), []int{4}
}

func (x *DoorState) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

type DoorStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	House         *House                 `protobuf:"bytes,1,opt,name=house,proto3" json:"house,omitempty"`
	Door          *Door                  `protobuf:"bytes,2,opt,name=door,proto3" json:"door,omitempty"`
	State         *DoorState             `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoorStatus) Reset() {
	*x = DoorStatus{}
	mi := &file_chough_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoorStatus) ProtoMessage() {}

func (x *DoorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_chough_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoorStatus.ProtoReflect.Descriptor instead.
func (*DoorStatus) Descriptor() ([]byte, []int) {
	return file_chough_proto_rawDescGZIP(), []int{5}
}

func (x *DoorStatus) GetHouse() *House {
	if x != nil {
		return x.House
	}
	return nil
}

func (x *DoorStatus) GetDoor() *Door {
	if x != nil {
		return x.Door
	}
	return nil
}

func (x *DoorStatus) GetState() *DoorState {
	if x != nil {
		return x.State
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_chough_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_chough_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_chough_proto_rawDescGZIP(), []int{6}
}

var File_chough_proto protoreflect.FileDescriptor

var file_chough_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x63, 0x68, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x63, 0x68, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x6d, 0x73, 0x67, 0x22, 0x43, 0x0a, 0x0d, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x43, 0x0a, 0x0d, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x17, 0x0a, 0x05, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x16, 0x0a,
	0x04, 0x44, 0x6f, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x09, 0x44, 0x6f, 0x6f, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x22, 0x88, 0x01, 0x0a, 0x0a, 0x44, 0x6f, 0x6f, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x68, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x05, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x24,
	0x0a, 0x04, 0x64, 0x6f, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63,
	0x68, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x44, 0x6f, 0x6f, 0x72, 0x52, 0x04,
	0x64, 0x6f, 0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x68, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x44, 0x6f, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x88, 0x03, 0x0a, 0x0d, 0x43,
	0x68, 0x6f, 0x75, 0x67, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x2e, 0x63, 0x68, 0x6f, 0x75,
	0x67, 0x68, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x63,
	0x68, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x10, 0x46, 0x6c, 0x75, 0x73, 0x68,
	0x53, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x2e, 0x63, 0x68,
	0x6f, 0x75, 0x67, 0x68, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11,
	0x2e, 0x63, 0x68, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x3e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x11, 0x2e, 0x63, 0x68, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x63, 0x68, 0x6f, 0x75, 0x67, 0x68, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x46, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x19, 0x2e, 0x63, 0x68, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x19,
	0x2e, 0x63, 0x68, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x0f, 0x46, 0x6c, 0x75,
	0x73, 0x68, 0x48, 0x6f, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x2e, 0x63,
	0x68, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x1a,
	0x11, 0x2e, 0x63, 0x68, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x41, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x44, 0x6f, 0x6f, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x2e, 0x63, 0x68, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x44, 0x6f, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x19, 0x2e, 0x63, 0x68, 0x6f,
	0x75, 0x67, 0x68, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_chough_proto_rawDescOnce sync.Once
	file_chough_proto_rawDescData []byte
)

func file_chough_proto_rawDescGZIP() []byte {
	file_chough_proto_rawDescOnce.Do(func() {
		file_chough_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chough_proto_rawDesc), len(file_chough_proto_rawDesc)))
	})
	return file_chough_proto_rawDescData
}

var file_chough_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_chough_proto_goTypes = []any{
	(*StatusMessage)(nil), // 0: chough.msg.StatusMessage
	(*ReturnMessage)(nil), // 1: chough.msg.ReturnMessage
	(*House)(nil),         // 2: chough.msg.House
	(*Door)(nil),          // 3: chough.msg.Door
	(*DoorState)(nil),     // 4: chough.msg.DoorState
	(*DoorStatus)(nil),    // 5: chough.msg.DoorStatus
	(*Empty)(nil),         // 6: chough.msg.Empty
}
var file_chough_proto_depIdxs = []int32{
	2, // 0: chough.msg.DoorStatus.house:type_name -> chough.msg.House
	3, // 1: chough.msg.DoorStatus.door:type_name -> chough.msg.Door
	4, // 2: chough.msg.DoorStatus.state:type_name -> chough.msg.DoorState
	6, // 3: chough.msg.ChoughService.GetStatus:input_type -> chough.msg.Empty
	6, // 4: chough.msg.ChoughService.FlushSoundStatus:input_type -> chough.msg.Empty
	6, // 5: chough.msg.ChoughService.GetSoundStatus:input_type -> chough.msg.Empty
	0, // 6: chough.msg.ChoughService.SetSoundStatus:input_type -> chough.msg.StatusMessage
	2, // 7: chough.msg.ChoughService.FlushHomeStatus:input_type -> chough.msg.House
	5, // 8: chough.msg.ChoughService.SetDoorState:input_type -> chough.msg.DoorStatus
	0, // 9: chough.msg.ChoughService.GetStatus:output_type -> chough.msg.StatusMessage
	6, // 10: chough.msg.ChoughService.FlushSoundStatus:output_type -> chough.msg.Empty
	0, // 11: chough.msg.ChoughService.GetSoundStatus:output_type -> chough.msg.StatusMessage
	0, // 12: chough.msg.ChoughService.SetSoundStatus:output_type -> chough.msg.StatusMessage
	6, // 13: chough.msg.ChoughService.FlushHomeStatus:output_type -> chough.msg.Empty
	1, // 14: chough.msg.ChoughService.SetDoorState:output_type -> chough.msg.ReturnMessage
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chough_proto_init() }
func file_chough_proto_init() {
	if File_chough_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chough_proto_rawDesc), len(file_chough_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chough_proto_goTypes,
		DependencyIndexes: file_chough_proto_depIdxs,
		MessageInfos:      file_chough_proto_msgTypes,
	}.Build()
	File_chough_proto = out.File
	file_chough_proto_goTypes = nil
	file_chough_proto_depIdxs = nil
}
